<?php
$con = new mysqli("localhost", "root", "", "qr_code_generator");
if ($con->connect_error) {
    die("Connection failed: " . $con->connect_error);
}

// Get current month and year
$currentMonth = date('m');
$currentYear = date('Y');  

// Fetch transactions only for the current month and year
// $sql = "SELECT id, start_serial, end_serial, excluded_serials, generated_at, user, qr_code_image 
//         FROM transaction_log 
//         WHERE MONTH(generated_at) = ? AND YEAR(generated_at) = ? 
//         ORDER BY generated_at DESC";
$sql = "SELECT id, product_type, start_serial, end_serial, excluded_serials, generated_at, user, qr_code_image 
        FROM transaction_log 
        WHERE MONTH(generated_at) = ? AND YEAR(generated_at) = ? 
        ORDER BY generated_at DESC";

$stmt = $con->prepare($sql);
$stmt->bind_param("ii", $currentMonth, $currentYear);
$stmt->execute();
$result = $stmt->get_result();

$con->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaction Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 50px;
            background-color: #f8f9fa;
            background: #f5f5f5 url('images/SIRIMbg.jpg') no-repeat center top fixed;
            background-size: cover;
        }

        .transaction-container {
            max-width: 800px;
            margin: 20px auto;
        }

        h2 {
            text-align: center;
        }

        h3 {
            text-align: center;
        }

        #clock {
            font-size: 18px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }

        .transaction-card {
            padding: 15px;
            border-radius: 10px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
            background-color: #fff;
            margin-bottom: 10px;
        }

        .transaction-info p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
<div class="transaction-container">
    <h2>Transaction Report</h2>
    <h3><?= date("F Y") ?></h1>
    <!-- <div id="clock"></div> -->

    <?php if ($result->num_rows > 0): ?>
        <?php while ($row = $result->fetch_assoc()): ?>
            <div class="transaction-card">
                <div class="transaction-info">
                    <p><strong>Product Type:</strong> <?= htmlspecialchars($row['product_type']) ?></p>
                    <p><strong>Start Serial:</strong> <?= htmlspecialchars($row['start_serial']) ?></p>
                    <p><strong>End Serial:</strong> <?= htmlspecialchars($row['end_serial']) ?></p>
                    <p><strong>Excluded Serials:</strong> <?= htmlspecialchars($row['excluded_serials']) ?></p>
                    <p><strong>Timestamp:</strong> <?= htmlspecialchars($row['generated_at']) ?></p>
                    <p><strong>Generated By:</strong> <?= htmlspecialchars($row['user']) ?></p>
                </div>
            </div>
        <?php endwhile; ?>
    <?php else: ?>
        <p style="text-align: center;">No transactions found for this month.</p>
    <?php endif; ?>
</div>

<script>
function updateClock() {
    const now = new Date();
    const hours = now.getHours().toString().padStart(2, '0');
    const minutes = now.getMinutes().toString().padStart(2, '0');
    const seconds = now.getSeconds().toString().padStart(2, '0');
    const formattedTime = `${hours}:${minutes}:${seconds}`;
    
    document.getElementById('clock').textContent = formattedTime;
}

// Update clock every second
setInterval(updateClock, 1000);

// Call it once to display immediately
updateClock();
</script>


</body>
</html>
